version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: payments-balancer
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - node
  db:
    image: postgres:latest
    container_name: payments-db
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: payments-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db

  node:
    build:
      context: ./api # Ruta de la carpeta que contiene tu aplicación Node.js
    container_name: payments-node
    environment:
      - POSTGRES_DATABASE=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - INITIALIZATION_DATABASE=0
      - JWT_SECRET=1d3pr01fd
      - BCRYPT_SALT_ROUNDS=10
      - JWT_TIME_EXPIRY=365d

    ports:
      - "6001:6001"
    depends_on:
      - db
